version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - .env

  web:
    image: arsenyrazumovsky/foodgram:latest
    volumes:
      - static_value:/app/web_static/
      - media_value:/app/web_media/
    expose:
      - 8000
    restart: always
    env_file:
      - .env
    depends_on:
      - db


  frontend:
    image: arsenyrazumovsky/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/app/web_static/
      - media_value:/app/web_media/
    depends_on:
      - frontend

volumes:
  postgres_data:
  static_value:
  media_value: