# Generated by Django 2.2.19 on 2022-08-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_auto_20220802_1638"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Время приготовления"
            ),
        ),
    ]
